development:
  adapter: postgresql
  host: localhost
  database: plane_finder_development
  
test:
  adapter: postgresql
  encoding: unicode
  database: plane_finder_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: plane_finder_production
  pool: 5
